name: Check Offical Portal SDK Version
on:
  workflow_dispatch:
  push:
env:
  PORTAL_SDK_VERSION: "1.0.1.0"
  PORTAL_SDK_SIZE: "2419712762"
  VERSION_COUNT: "1"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Get Offical Portal Version Info
        run: echo "SDK_VERSION_INFO=$(curl https://download.portal.battlefield.com/versions.json)" >> $GITHUB_ENV
      - name: Extract Version, File Size, and Version Count
        run: |
          VERSION=$(echo "$SDK_VERSION_INFO" | jq -r '.versions | last | .version')
          FILE_SIZE=$(echo "$SDK_VERSION_INFO" | jq -r '.versions | last | .fileSize')
          VERSION_COUNT=$(echo "$SDK_VERSION_INFO" | jq -r '.versionCount')
          echo "NEW_SDK_VERSION=$VERSION" >> $GITHUB_ENV
          echo "NEW_SDK_SIZE=$FILE_SIZE" >> $GITHUB_ENV
          echo "NEW_VERSION_COUNT=$VERSION_COUNT" >> $GITHUB_ENV
      - name: Check Version Count
        id: check_version_count
        run: |
          if [ "$VERSION_COUNT" != "$NEW_VERSION_COUNT" ]; then
            echo "version_count_changed=true" >> $GITHUB_OUTPUT
            echo "Version count changed $VERSION_COUNT -> $NEW_VERSION_COUNT"
          else
            echo "version_count_changed=false" >> $GITHUB_OUTPUT
            echo "Version and size check skipped."
          fi
      - name: Check Version and Size Difference
        if: steps.check_version_count.outputs.version_count_changed == 'true'
        run: |
          if [ "$PORTAL_SDK_VERSION" != "$NEW_SDK_VERSION" ]; then
            echo "::warning title=Version Mismatch::Portal SDK version has changed.  Old: $PORTAL_SDK_VERSION, New: $NEW_SDK_VERSION"
          fi
          if [ "$PORTAL_SDK_SIZE" != "$NEW_SDK_SIZE" ]; then
            echo "::warning title=Size Mismatch::Portal SDK size has changed. Old: $PORTAL_SDK_SIZE, New: $NEW_SDK_SIZE"
          fi
          if [ "$PORTAL_SDK_VERSION" == "$NEW_SDK_VERSION" ] || [ "$PORTAL_SDK_SIZE" == "$NEW_SDK_SIZE" ]; then
            echo "Version and size match."
          fi
      - name: Send Alert to discord
        if: steps.check_version_count.outputs.version_count_changed == 'true'
        uses: appleboy/discord-action@v1.2.0
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          username: "PortalSDK Version Tracker"
          message: ":bf6: <@916729041002852363>\n### New Version of Official SDK Available.\nNew Version: `${{ env.NEW_SDK_VERSION }}`\nNew Size: `${{ env.NEW_SDK_SIZE }}`\n[Download](https://download.portal.battlefield.com/PortalSDK.zip)"