name: Check Offical Portal SDK Version
on:
  workflow_dispatch:

env:
  PORTAL_SDK_VERSION: "1.0.1.0"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Get Offical Portal Version Info
        run: curl https://download.portal.battlefield.com/versions.json | jq '.'
      # - name: send custom message
      #   uses: appleboy/discord-action@v1.2.0
      #   with:
      #     webhook_url: ${{ secrets.WEBHOOK_URL }}
      #     message: New PortalSDK version Available. 